### ISSUE TITLE
Build failure using Clang 13.1.6 due to googletest submodule

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#1369]
I am trying to build `prestosql/tests/ArithmeticTest.cpp` on my Mac with Clang 13.1.6 and it fails with the following error.
This was also reported here. https://github.com/facebookincubator/velox/issues/1286#issuecomment-1086595439
Essentially, `-Werror` is set by default and warnings are erroring out. The fix for this is merged in googletest commit https://github.com/google/googletest/commit/f7902802f1a61140e188223fb6d1c95925cbec4a

```
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock.h:59:
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
  ^
/usr/local/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-actions.h:1011:10: note: in implicit copy constructor for 'testing::PolymorphicAction<testing::internal::ReturnNullAction>' first required here
  return MakePolymorphicAction(internal::ReturnNullAction());
         ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-actions.h:455:3: error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnVoidAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
  ^
/usr/local/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-actions.h:1016:10: note: in implicit copy constructor for 'testing::PolymorphicAction<testing::internal::ReturnVoidAction>' first required here
  return MakePolymorphicAction(internal::ReturnVoidAction());
         ^
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock.h:61:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-function-mocker.h:39:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:47:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:1506:3: error: definition of implicit copy constructor for 'FloatingEqMatcher<double>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(FloatingEqMatcher);
  ^
/usr/local/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:3632:10: note: in implicit copy constructor for 'testing::internal::FloatingEqMatcher<double>' first required here
  return internal::FloatingEqMatcher<double>(rhs, false);
         ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:1506:3: error: definition of implicit copy constructor for 'FloatingEqMatcher<float>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(FloatingEqMatcher);
  ^
/usr/local/include/gtest/internal/gtest-port.h:682:8: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
       ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:3660:10: note: in implicit copy constructor for 'testing::internal::FloatingEqMatcher<float>' first required here
  return internal::FloatingEqMatcher<float>(rhs, false);
```

**Comment by mbasmanova** [comment]
I ran into the same issue on my Mac and edited the googletest to workaround. Perhaps, we can upgrade to 1.11? CC: @wenleix @kgpai

**Comment by majetideepak** [comment]
After the recent upgrade to 11.0, I now get the following error
```
[ 13%] Building CXX object velox/functions/lib/string/tests/CMakeFiles/velox_functions_string_test.dir/StringImplTest.cpp.o
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock.h:61:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-function-mocker.h:42:
In file included from /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:3165:49: error: use of undeclared identifier 'IndexSequenceFor'
        new FieldsAreMatcherImpl<const Struct&, IndexSequenceFor<Inner...>>(
                                                ^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:4291:21: error: no template named 'StringLike' in namespace 'testing::internal'
    const internal::StringLike<T>& str) {
          ~~~~~~~~~~^
/Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:4299:21: error: no template named 'StringLike' in namespace 'testing::internal'
    const internal::StringLike<T>& str) {

```

**Comment by kgpai** [comment]
@majetideepak This pr by @kagamiori should fix the problem https://github.com/facebookincubator/velox/pull/1325.

**Comment by kagamiori** [comment]
> @majetideepak This pr by @kagamiori should fix the problem #1325. I presume you mean upgrading to gtest 1.10 .

Actually, my PR fixes errors in GTest 1.10 by upgrading to GTest 1.11. I didn't have these errors on my mac when using GTest 1.11 and MacOSX12.3.sdk. My clang version is also 13.1.6. @majetideepak Which GTest and MacOS SDK version are you using?

**Comment by majetideepak** [comment]
My bad, I did mean GTest 1.11 that landed today on main. My SDK is also MacOSX12.3.sdk.
@kagamiori are you able to build `velox/functions/prestosql/tests/ArithmeticTest.cpp` ?
Can you try deleting the build directory and try from a clean state?

**Comment by kagamiori** [comment]
Hi @majetideepak, I just tried again on my mac by git clone the latest Velox repository and build everything from scratch (in a new directory I never used before, so I think it has a clean state). I didn't got any error and I double-checked that velox/functions/prestosql/tests/ArithmeticTest.cpp is built.

**Comment by majetideepak** [comment]
@kagamiori thanks for taking the time to check this. I am still seeing this. Let's keep it open to see if anybody else is hitting this.

**Comment by parmeet** [comment]
> @kagamiori thanks for taking the time to check this. I am still seeing this. Let's keep it open to see if anybody else is hitting this.

Thanks! I am seeing same issue on my side as well while compiling latest main of TorchArrow. cc: @wenleix, @kgpai

**Comment by mbasmanova** [comment]
CC: @spershin

**Comment by mbasmanova** [comment]
> /Users/deepak/workspace/ahana/velox/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:3165:49: error: use of undeclared identifier 'IndexSequenceFor'

@majetideepak @Nayef211 Deepak, Nayef, I see that IndexSequenceFor is defined in googletest/include/gtest/internal/gtest-internal.h

https://chromium.googlesource.com/external/github.com/google/googletest/+/HEAD/googletest/include/gtest/internal/gtest-internal.h

```
template <typename... T>
  | using IndexSequenceFor = typename MakeIndexSequence<sizeof...(T)>::type;
```

Would you check if you have that file and if it has the code above?

**Comment by majetideepak** [comment]
@mbasmanova the file and the code exist. I am also able to build googletest as a standalone CLion project. But for some reason, it fails as a submodule build in Velox.

**Comment by majetideepak** [comment]
I had to delete my local `gtest`, `gmock` install headers (`/usr/local/include/gtest`, `/usr/local/include/gmock`) to resolve this. This is not ideal for all users as they might need these for other projects.

We should move towards the `ExternalProject_Add()` approach sooner and allow users to choose between external deps vs. submodules build.

**Comment by majetideepak** [comment]
@mbasmanova thanks for your comment to check that header! That lead me on the path of discovering this.
I noticed my local headers were being included in the build.

**Comment by mbasmanova** [comment]
@majetideepak Deepak, I now remember that I also had to mode/delete the gtest headers from /usr/local/include as these were used instead of the one in the submodule. @Nayef211 @parmeet Is this something you could try as a workaround.

@kgpai Krishna, let's look into why we are using the headers from the "wrong" location.

**Comment by Nayef211** [comment]
> @majetideepak Deepak, I now remember that I also had to mode/delete the gtest headers from /usr/local/include as these were used instead of the one in the submodule. @Nayef211 @parmeet Is this something you could try as a workaround.

This worked for me @mbasmanova! I also ran into the following error after the recent MacOS update coming from third party libraries

```
non-existent path "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include"
```

I was able to resolve this by creating a symlink from `MacOSX12.3.sdk` to `MacOSX12.1.sdk`

**Comment by majetideepak** [comment]
> non-existent path "/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include"
> I was able to resolve this by creating a symlink from `MacOSX12.3.sdk` to `MacOSX12.1.sdk`

@Nayef211 A clean build by deleting the build directory should resolve this. No need to create the symlink.

**Comment by kgpai** [comment]
Hi , @majetideepak , I will work on porting gtest along with other and future dependencies to ExternalProject_Add which will first look for external deps and then fallback to our specified submodules should they fail to exist.

**Comment by kgpai** [comment]
FYI, Also I believe theres a bug in our build scripts that makes it look into /usr/local instead of using submodule provided. Will look into that too.

**Comment by leoYY** [comment]
Hi, @mbasmanova I also encountered the same error in my workspace.
And I found that
```
// CMakeLists.txt
find_package(
  Boost
  ...
  atomic)
include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
```
${Boost_INCLUDE_DIRS} = '/usr/local/include' 
It make compile command for gtest  like 

```
  g++ ... -I{gmock_include_path} -isystem /usr/local/include ... -isystem ${real_gtest_include_path} ...
```
I hope this may help.

**Comment by mbasmanova** [comment]
> I believe theres a bug in our build scripts that makes it look into /usr/local instead of using submodule provided. Will look into that too.

@kgpai Any update on this?
