### ISSUE TITLE
Enhance Presto coverage maps to also include function signatures 

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#5905]
### Description

Today, the coverage scripts can be used to generate Presto function coverage maps like https://facebookincubator.github.io/velox/functions/presto/coverage.html. 

This coverage map is based on function names only and does not include function signatures. So its hard to trace if all variations of a function with multiple signatures are available in Velox.

Signature based coverage would be really helpful.

**Comment by aditi-pandit** [comment]
@yzhang1991

**Comment by Ann-Rose** [comment]
Looks like `velox/velox/functions/prestosql/coverage/Coverage.cpp `  is the file that generates the executable `velox_prestosql_coverage`

**Comment by aditi-pandit** [comment]
> Looks like `velox/velox/functions/prestosql/coverage/Coverage.cpp ` is the file that generates the executable `velox_prestosql_coverage`
> 
> This generates the coverage after running the SHOW FUNCTIONS in presto and generating 3 files: all_scalar_functions.txt all_aggregate_functions.txt all_window_functions.txt
> 
> CoverageUtil.cpp contains a function `printCoverageMap` that takes this input and checks if it is implemented in velox and creates the coverageMap

@Ann-Rose : Yes, that is right. These need to be updated to also include function signatures as well.

**Comment by Ann-Rose** [comment]
@aditi-pandit The existing implementation looks like this
<img width="1512" alt="Screenshot 2023-08-14 at 4 38 51 PM" src="https://github.com/facebookincubator/velox/assets/126868353/73d84eb8-9d1f-4f6f-bf00-a5b91bad8f99">

But for some function names, we have more than 7 signatures.. So, It looks like it is not possible to incorporate function names and signatures in the existing format/design.  Can we print each function with its signatures line by line.

**Comment by aditi-pandit** [comment]
> @aditi-pandit The existing implementation looks like this <img alt="Screenshot 2023-08-14 at 4 38 51 PM" width="1512" src="https://user-images.githubusercontent.com/126868353/260432328-73d84eb8-9d1f-4f6f-bf00-a5b91bad8f99.png">
> 
> But for some function names, we have more than 7 signatures.. So, It looks like it is not possible to incorporate function names and signatures in the existing format/design. Can we print each function with its signatures line by line.

@Ann-Rose : In general, its alright to change the format. But I feel we should leave this chart as is and generate a second chart which includes signatures.

**Comment by ashokku2022** [comment]
@aditi-pandit could you provide an example (pick any function and their signatures) on how you would like display them. This would give clarity. IMO as a user I would like to see (example: `abs` function)
func: abs
func: abs(real, real)
func: abs (decimal, decimal)
func: abs (int, int)
.....
........

**Comment by aditi-pandit** [comment]
> @aditi-pandit could you provide an example (pick any function and their signatures) on how you would like display them. This would give clarity. IMO as a user I would like to see (example: `abs` function) func: abs func: abs(real, real) func: abs (decimal, decimal) func: abs (int, int) ..... ........

@ashokku2022, @Ann-Rose :
Lets do a bit more analysis before deciding the display format. It might be worth generating a list of all the functions with all the signatures. Like Ann suggested we can have a chart with each function signature line by line. Once we get an idea about how big that is then we can decide some other format to make it more easy to read.

**Comment by Ann-Rose** [comment]
@aditi-pandit @ashokku2022 Currently this is is how the output is presented line by line [outputfile](https://github.com/facebookincubator/velox/files/12361570/something15.txt)

**Comment by aditi-pandit** [comment]
@Ann-Rose : This looks like a good first step. Is it possible to generate an html out of this so that its easier to visualize ? Also, would you be able to highlight the ones migrated already in the chart ?

**Comment by Ann-Rose** [comment]
On generating html out of this. 

The existing view for all the velox functions:
<img width="1490" alt="Screenshot 2023-08-22 at 9 51 02 PM" src="https://github.com/facebookincubator/velox/assets/126868353/ef260bb3-1ba8-4735-a80b-f60ea6eb674b">


After my changes, the view for all the velox functions looks like this (still have to make some changes related to adding breaks between signatures) :
<img width="1490" alt="Screenshot 2023-08-22 at 9 51 53 PM" src="https://github.com/facebookincubator/velox/assets/126868353/ffc5c567-41b8-4050-892f-b51cc0ca261e">

**Comment by Ann-Rose** [comment]
On generating html out of all the presto functions with velox functions highlighted:

The existing view:

![image](https://github.com/facebookincubator/velox/assets/126868353/7646ab22-cf86-40a3-8b84-a1f5a1bc4977)

The new view: ( This too needs additional formatting to include line breaks) 

![image](https://github.com/facebookincubator/velox/assets/126868353/9e5b82dc-eb78-41e4-b96e-23c655f75123)

**Comment by majetideepak** [comment]
@aditi-pandit, @Ann-Rose I feel we should keep the existing view as it is concise.
We can add a link to the new view from the old view. What do you think?
It would be great if we can add a hyperlink for each function in the old view to the corresponding entry in the new view if that can be automated.

**Comment by aditi-pandit** [comment]
@majetideepak : We are leaving the current chart as is. This is a new chart.

The new chart will definitely be linked from the old one. and we will try to link individual entries also. Updating the issue description.

**Comment by majetideepak** [comment]
@aditi-pandit thanks for clarifying. I saw `existing view`, `new view` in the comments above. So I felt the current chart was going away.

**Comment by Ann-Rose** [comment]
@aditi-pandit  I have updated the PR

The functionality of  
``` 
      velox_prestosql_coverage 
      velox_prestosql_coverage --all
      velox_prestosql_coverage --most_used
 ```
 remains the same. I have added  
```
velox_prestosql_coverage --signatures
``` 
to generate all the existing velox functions and their signatures, 
```
velox_prestosql_coverage --all_signatures
``` 
to generate coverage map for all Presto functions along with their signatures, and 
```
velox_prestosql_coverage --most_used_signatures
``` 
to generate coverage map for a subset of most-used Presto functions along with their signatures

**Comment by Ann-Rose** [comment]
How are we generating these files:

```
1. all_scalar_functions.txt
2. all_aggregate_functions.txt
3. all_window_functions.txt
4. most_used_functions.txt
```
Scalar functions like classify and features are not available in the output of SHOW FUNCTIONS but these are present in all_scalar_functions.txt

**Comment by Ann-Rose** [comment]
Implemented logic to compare presto and velox signatures and display all the presto functions and its signatures with those signatures that are present in both presto and velox highlighted. But there are few problems that I am facing:
1.  First being the intermediate type being represented in velox whereas presto doesnt have this in the signatures.
    Example:
    
    ```
    (T,boolean) -> row(T,boolean) -> T
    ```
2. Decimal representation is differently represented in presto and velox:
     In Presto: 
     
      ```  
      (decimal(p,s)) -> decimal(p,s)
      ```
     In Velox:
        
      ```
       (DECIMAL(a_precision,a_scale)) -> DECIMAL(a_precision,a_scale)
      ```
3. There are space differences in the signature representation in presto and velox
<img width="1120" alt="Screenshot 2023-09-07 at 4 56 27 PM" src="https://github.com/facebookincubator/velox/assets/126868353/422a0856-16f2-436d-8e23-ab5aa9ce8a55">


4.  Also in presto there are abbreviations  E, T etc. which are not represented the same way in velox
<img width="1120" alt="Screenshot 2023-09-07 at 4 58 04 PM" src="https://github.com/facebookincubator/velox/assets/126868353/1f382e79-e66e-4bb1-9597-e7b036f81942">
.

**Comment by yzhang1991** [comment]
@aditi-pandit reping

**Comment by aditi-pandit** [comment]
> @aditi-pandit
> 
> The table below contains the differences between the way function signatures are being represented in presto and velox. ( Some of these can be handled, like the comma separator, intermediate representation, etc.. but others dont follow a pattern in representation) Do you have inputs on how to handle these or which representation to use?
> 
> <img alt="Screenshot 2023-10-06 at 9 57 11 PM" width="1418" src="https://user-images.githubusercontent.com/126868353/273276014-ba6bd255-c8b0-4d77-bae4-60a8eb038595.png">

@Ann-Rose  : Thanks Ann. Your question is more clear now.

- For DECIMAL we should map Velox p => Presto a_precision, s => a_scale. This is expected and we should fix the format and compare.
- The script should ignore casing differences for types e.g. in nth_value signature.
- The script should ignore spaces in comparisons.
- For aggregate functions: Velox gives a signature with format (raw, partial, final), whereas Presto gives only raw -> final signature. We will need to process Velox signature to a Presto compatible format and compare.

The other 2 cases you have are more interesting and need thought

- GENERALIZATION: In the array_distinct case, Velox doesn't seem to handle DECIMAL type among others. For greatest function, it doesn't handle complex types like arrays, maps and structs. So we will have to think about what is the universal set for E in Presto and check if there are Velox signatures for all possible cases of E. 
- VARCHAR DIFFERENT REPRESENTATION : Velox doesn't support varchar(n). It supports only varchar (without an upper limit on length). Presto supports both Varchar and Varchar(n). Velox maps varchar(n) to varchar losing the length requirement. So in function comparison 
   i) Its important that all varchar(n) signatures in Presto have a Velox equivalent with varchar. 
   ii) But in the script we add a warning for the functions (that are varchar(n) and not varchar) that max length limit is not enforced.

**Comment by Ann-Rose** [comment]
@aditi-pandit  Thanks

To make this more clear, the following is to be done:
1. We should change the decimal representation to the way it is represented in velox, like DECIMAL(a_precision, a_scale)
2. Ignore case difference and space differences. 
3. Make the velox aggregate functions to presto representation that is without the partial arguments.

4. We are still not sure about how to handle the array_distinct and greatest function cases that involve generalization. 

But I didnot quite understand how to handle the last case. 
Do you mean presto varchar(n) equivalent will be varchar in velox, but we have to display warning that the max length limit is not enforced?

**Comment by aditi-pandit** [comment]
@Ann-Rose : Yes.

**Comment by Ann-Rose** [comment]
Made all the other changes except for handling the universal set issue mentioned in the 5th point here https://github.com/facebookincubator/velox/issues/5905#issuecomment-1756351075. Need clarity on what corresponds to the universal set E and T.
